### PR TITLE
RichText support added

### PR DESCRIPTION
**Pull request by tumms2021389**
Test cases has been added on Lab5304 server under Form Fields

### CODE REVIEW

**Comment by JEAxero** [comment]
A few things I noticed:

- This PR is to commit to master (which is for 23.1) and lab5304 is an 8.8 server
- We need to figure out why there's a lint error shown in one of the checks above

**Review by JEAxero — CHANGES_REQUESTED** [review]
A few things I noticed:

- This PR is to commit to master (which is for 23.1) and lab5304 is an 8.8 server - so this should likely be targeted to be merged into the release/8.8.20 branch

- However, when I run the Digv2 tests against lab5304, only 6 pass. So we'll need to understand/fix that before this PR is merged.

- We need to figure out why there's a lint error shown in one of the checks above

**Review by JEAxero — APPROVED** [review]
Though I am only able to run the new richtext test on an 8.8 machine, I'm approving this PR since I was able to confirm that the other tests are ok on a 23.1 machine. So, I've reviewed, tested, and approved this PR. However, note that we **need a similar PR for the release/8.8.20** branch, too. Thanks!

**Comment by paulgagnon-pega** [comment]
Siva, I see these errors when I try and build with your branch..

[build-dev-only] ERROR in ./packages/react-sdk-components/src/components/designSystemExtension/RichTextEditor/RichTextEditor.tsx 837:0-48
[build-dev-only] Module not found: Error: Can't resolve '@tinymce/tinymce-react' in '/Users/gagnp/approvals/React/23.1/react-sdk-components/packages/react-sdk-components/src/components/designSystemExtension/RichTextEditor'
[build-dev-only]  @ ./packages/react-sdk-components/src/components/designSystemExtension/RichTextEditor/index.tsx 40:0-43 40:0-43
[build-dev-only]  @ ./packages/react-sdk-components/src/components/field/RichText/RichText.tsx 804:0-72 864:44-58 919:44-58
[build-dev-only]  @ ./packages/react-sdk-components/src/components/field/RichText/index.tsx 40:0-37 40:0-37
[build-dev-only]  @ ./packages/react-sdk-components/src/sdk-pega-component-map.js 124:0-51 230:14-22
[build-dev-only]  @ ./packages/react-sdk-components/src/bridge/helpers/sdk_component_map.ts 1630:0-63 1719:88-107
[build-dev-only]  @ ./packages/react-sdk-components/src/samples/FullPortal/index.tsx 1392:0-76 1533:6-24
[build-dev-only]  @ ./packages/react-sdk-components/src/samples/AppSelector/index.tsx 105:0-39 134:15-25 137:15-25
[build-dev-only]  @ ./packages/react-sdk-components/src/samples/TopLevelApp/index.tsx 241:0-41 246:62-73
[build-dev-only]  @ ./packages/react-sdk-components/src/index.tsx 115:0-53 122:70-81
[build-dev-only] 
[build-dev-only] ERROR in unable to locate '/Users/gagnp/approvals/React/23.1/react-sdk-components/node_modules/tinymce' glob
[build-dev-only] 
[build-dev-only] ERROR in /Users/gagnp/approvals/React/23.1/react-sdk-components/packages/react-sdk-components/src/components/designSystemExtension/RichTextEditor/RichTextEditor.tsx
[build-dev-only] ./packages/react-sdk-components/src/components/designSystemExtension/RichTextEditor/RichTextEditor.tsx 2:23-47
[build-dev-only] [tsl] ERROR in /Users/gagnp/approvals/React/23.1/react-sdk-components/packages/react-sdk-components/src/components/designSystemExtension/RichTextEditor/RichTextEditor.tsx(2,24)
[build-dev-only]       TS2307: Cannot find module '@tinymce/tinymce-react' or its corresponding type declarations.
[build-dev-only]  @ ./packages/react-sdk-components/src/components/designSystemExtension/RichTextEditor/index.tsx 40:0-43 40:0-43
[build-dev-only]  @ ./packages/react-sdk-components/src/components/field/RichText/RichText.tsx 804:0-72 864:44-58 919:44-58
[build-dev-only]  @ ./packages/react-sdk-components/src/components/field/RichText/index.tsx 40:0-37 40:0-37
[build-dev-only]  @ ./packages/react-sdk-components/src/sdk-pega-component-map.js 124:0-51 230:14-22
[build-dev-only]  @ ./packages/react-sdk-components/src/bridge/helpers/sdk_component_map.ts 1630:0-63 1719:88-107
[build-dev-only]  @ ./packages/react-sdk-components/src/samples/FullPortal/index.tsx 1392:0-76 1533:6-24
[build-dev-only]  @ ./packages/react-sdk-components/src/samples/AppSelector/index.tsx 105:0-39 134:15-25 137:15-25
[build-dev-only]  @ ./packages/react-sdk-components/src/samples/TopLevelApp/index.tsx 241:0-41 246:62-73
[build-dev-only]  @ ./packages/react-sdk-components/src/index.tsx 115:0-53 122:70-81
[build-dev-only] 
[build-dev-only] 1 error has detailed information that is not shown.
[build-dev-only] Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.
[build-dev-only] 
[build-dev-only] webpack 5.76.1 compiled with 3 errors in 39504 ms
ERROR: "build-dev-only" exited with 1.

**Comment by JEAxero** [comment]
Paul:

You probably need to do an npm install or an npm run build:dev:ci to get the new tinymce package installed

- John -

From: paulgagnon-pega ***@***.***>
Date: Thursday, November 2, 2023 at 10:34 AM
To: pegasystems/react-sdk-components ***@***.***>
Cc: Arnold, John ***@***.***>, Review requested ***@***.***>
Subject: ExtMsg: Re: [pegasystems/react-sdk-components] RichText support added (PR #205)
CAUTION: This email was sent from an EXTERNAL source. Think before clicking links or opening attachments.


Siva, I see these errors when I try and build with your branch..

[build-dev-only] ERROR in ./packages/react-sdk-components/src/components/designSystemExtension/RichTextEditor/RichTextEditor.tsx 837:0-48
[build-dev-only] Module not found: Error: Can't resolve ***@***.***/tinymce-react' in '/Users/gagnp/approvals/React/23.1/react-sdk-components/packages/react-sdk-components/src/components/designSystemExtension/RichTextEditor'
[build-dev-only] @ ./packages/react-sdk-components/src/components/designSystemExtension/RichTextEditor/index.tsx 40:0-43 40:0-43
[build-dev-only] @ ./packages/react-sdk-components/src/components/field/RichText/RichText.tsx 804:0-72 864:44-58 919:44-58
[build-dev-only] @ ./packages/react-sdk-components/src/components/field/RichText/index.tsx 40:0-37 40:0-37
[build-dev-only] @ ./packages/react-sdk-components/src/sdk-pega-component-map.js 124:0-51 230:14-22
[build-dev-only] @ ./packages/react-sdk-components/src/bridge/helpers/sdk_component_map.ts 1630:0-63 1719:88-107
[build-dev-only] @ ./packages/react-sdk-components/src/samples/FullPortal/index.tsx 1392:0-76 1533:6-24
[build-dev-only] @ ./packages/react-sdk-components/src/samples/AppSelector/index.tsx 105:0-39 134:15-25 137:15-25
[build-dev-only] @ ./packages/react-sdk-components/src/samples/TopLevelApp/index.tsx 241:0-41 246:62-73
[build-dev-only] @ ./packages/react-sdk-components/src/index.tsx 115:0-53 122:70-81
[build-dev-only]
[build-dev-only] ERROR in unable to locate '/Users/gagnp/approvals/React/23.1/react-sdk-components/node_modules/tinymce' glob
[build-dev-only]
[build-dev-only] ERROR in /Users/gagnp/approvals/React/23.1/react-sdk-components/packages/react-sdk-components/src/components/designSystemExtension/RichTextEditor/RichTextEditor.tsx
[build-dev-only] ./packages/react-sdk-components/src/components/designSystemExtension/RichTextEditor/RichTextEditor.tsx 2:23-47
[build-dev-only] [tsl] ERROR in /Users/gagnp/approvals/React/23.1/react-sdk-components/packages/react-sdk-components/src/components/designSystemExtension/RichTextEditor/RichTextEditor.tsx(2,24)
[build-dev-only] TS2307: Cannot find module ***@***.***/tinymce-react' or its corresponding type declarations.
[build-dev-only] @ ./packages/react-sdk-components/src/components/designSystemExtension/RichTextEditor/index.tsx 40:0-43 40:0-43
[build-dev-only] @ ./packages/react-sdk-components/src/components/field/RichText/RichText.tsx 804:0-72 864:44-58 919:44-58
[build-dev-only] @ ./packages/react-sdk-components/src/components/field/RichText/index.tsx 40:0-37 40:0-37
[build-dev-only] @ ./packages/react-sdk-components/src/sdk-pega-component-map.js 124:0-51 230:14-22
[build-dev-only] @ ./packages/react-sdk-components/src/bridge/helpers/sdk_component_map.ts 1630:0-63 1719:88-107
[build-dev-only] @ ./packages/react-sdk-components/src/samples/FullPortal/index.tsx 1392:0-76 1533:6-24
[build-dev-only] @ ./packages/react-sdk-components/src/samples/AppSelector/index.tsx 105:0-39 134:15-25 137:15-25
[build-dev-only] @ ./packages/react-sdk-components/src/samples/TopLevelApp/index.tsx 241:0-41 246:62-73
[build-dev-only] @ ./packages/react-sdk-components/src/index.tsx 115:0-53 122:70-81
[build-dev-only]
[build-dev-only] 1 error has detailed information that is not shown.
[build-dev-only] Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.
[build-dev-only]
[build-dev-only] webpack 5.76.1 compiled with 3 errors in 39504 ms
ERROR: "build-dev-only" exited with 1.

**Comment by paulgagnon-pega** [comment]
Yup, that fixed it.

From: J_Arnold ***@***.***>
Reply-To: pegasystems/react-sdk-components ***@***.***>
Date: Thursday, November 2, 2023 at 10:37 AM
To: pegasystems/react-sdk-components ***@***.***>
Cc: "Gagnon, Paul" ***@***.***>, Review requested ***@***.***>
Subject: ExtMsg: Re: [pegasystems/react-sdk-components] RichText support added (PR #205)

CAUTION: This email was sent from an EXTERNAL source. Think before clicking links or opening attachments.

Paul:

You probably need to do an npm install or an npm run build:dev:ci to get the new tinymce package installed

- John -

From: paulgagnon-pega ***@***.***>
Date: Thursday, November 2, 2023 at 10:34 AM
To: pegasystems/react-sdk-components ***@***.***>
Cc: Arnold, John ***@***.***>, Review requested ***@***.***>
Subject: ExtMsg: Re: [pegasystems/react-sdk-components] RichText support added (PR #205)
CAUTION: This email was sent from an EXTERNAL source. Think before clicking links or opening attachments.


Siva, I see these errors when I try and build with your branch..

[build-dev-only] ERROR in ./packages/react-sdk-components/src/components/designSystemExtension/RichTextEditor/RichTextEditor.tsx 837:0-48
[build-dev-only] Module not found: Error: Can't resolve ***@***.***/tinymce-react' in '/Users/gagnp/approvals/React/23.1/react-sdk-components/packages/react-sdk-components/src/components/designSystemExtension/RichTextEditor'
[build-dev-only] @ ./packages/react-sdk-components/src/components/designSystemExtension/RichTextEditor/index.tsx 40:0-43 40:0-43
[build-dev-only] @ ./packages/react-sdk-components/src/components/field/RichText/RichText.tsx 804:0-72 864:44-58 919:44-58
[build-dev-only] @ ./packages/react-sdk-components/src/components/field/RichText/index.tsx 40:0-37 40:0-37
[build-dev-only] @ ./packages/react-sdk-components/src/sdk-pega-component-map.js 124:0-51 230:14-22
[build-dev-only] @ ./packages/react-sdk-components/src/bridge/helpers/sdk_component_map.ts 1630:0-63 1719:88-107
[build-dev-only] @ ./packages/react-sdk-components/src/samples/FullPortal/index.tsx 1392:0-76 1533:6-24
[build-dev-only] @ ./packages/react-sdk-components/src/samples/AppSelector/index.tsx 105:0-39 134:15-25 137:15-25
[build-dev-only] @ ./packages/react-sdk-components/src/samples/TopLevelApp/index.tsx 241:0-41 246:62-73
[build-dev-only] @ ./packages/react-sdk-components/src/index.tsx 115:0-53 122:70-81
[build-dev-only]
[build-dev-only] ERROR in unable to locate '/Users/gagnp/approvals/React/23.1/react-sdk-components/node_modules/tinymce' glob
[build-dev-only]
[build-dev-only] ERROR in /Users/gagnp/approvals/React/23.1/react-sdk-components/packages/react-sdk-components/src/components/designSystemExtension/RichTextEditor/RichTextEditor.tsx
[build-dev-only] ./packages/react-sdk-components/src/components/designSystemExtension/RichTextEditor/RichTextEditor.tsx 2:23-47
[build-dev-only] [tsl] ERROR in /Users/gagnp/approvals/React/23.1/react-sdk-components/packages/react-sdk-components/src/components/designSystemExtension/RichTextEditor/RichTextEditor.tsx(2,24)
[build-dev-only] TS2307: Cannot find module ***@***.***/tinymce-react' or its corresponding type declarations.
[build-dev-only] @ ./packages/react-sdk-components/src/components/designSystemExtension/RichTextEditor/index.tsx 40:0-43 40:0-43
[build-dev-only] @ ./packages/react-sdk-components/src/components/field/RichText/RichText.tsx 804:0-72 864:44-58 919:44-58
[build-dev-only] @ ./packages/react-sdk-components/src/components/field/RichText/index.tsx 40:0-37 40:0-37
[build-dev-only] @ ./packages/react-sdk-components/src/sdk-pega-component-map.js 124:0-51 230:14-22
[build-dev-only] @ ./packages/react-sdk-components/src/bridge/helpers/sdk_component_map.ts 1630:0-63 1719:88-107
[build-dev-only] @ ./packages/react-sdk-components/src/samples/FullPortal/index.tsx 1392:0-76 1533:6-24
[build-dev-only] @ ./packages/react-sdk-components/src/samples/AppSelector/index.tsx 105:0-39 134:15-25 137:15-25
[build-dev-only] @ ./packages/react-sdk-components/src/samples/TopLevelApp/index.tsx 241:0-41 246:62-73
[build-dev-only] @ ./packages/react-sdk-components/src/index.tsx 115:0-53 122:70-81
[build-dev-only]
[build-dev-only] 1 error has detailed information that is not shown.
[build-dev-only] Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.
[build-dev-only]
[build-dev-only] webpack 5.76.1 compiled with 3 errors in 39504 ms
ERROR: "build-dev-only" exited with 1.

**Comment by JEAxero** [comment]
@tumms2021389 The typedefs for 23.1.10 are different than for 8.8.20 and there are some compilation errors that you'll need to fix for this to build/run correctly.

**Review by paulgagnon-pega — APPROVED** [review]

**Comment by tumms2021389** [comment]
> @tumms2021389 The typedefs for 23.1.10 are different than for 8.8.20 and there are some compilation errors that you'll need to fix for this to build/run correctly.

Fixed compilation errors

**Comment by tumms2021389** [comment]
As of now some tests in the lab0087 server are failing, @4manasa is looking to them. Inorder to tests these changes you can run only RichText playwright tests.

**Review by JEAxero — APPROVED** [review]
Reviewed. Tested (after finding a 23.1 machine with the new functionality). Approved.

**Pull request merged**
